# src/agents/query_understanding_agent.py

import os
import re
import json
from langchain_core.prompts import PromptTemplate
from pydantic import BaseModel, Field
from langchain_core.output_parsers import PydanticOutputParser
from langchain_core.output_parsers.base import BaseOutputParser
from langchain_huggingface.chat_models import ChatHuggingFace
from typing import Literal, Dict

# Step 1: Define the desired output structure using Pydantic.
# This acts as a strict "form" that the AI is required to fill out.
class ParsedQuery(BaseModel):
    """A structured representation of a user's query for the legal adviser."""
    intent: Literal["legal_research", "find_lawyer", "general_question"] = Field(
        description="The user's primary goal. Must be one of: 'legal_research', 'find_lawyer', or 'general_question'."
    )
    entities: Dict[str, str] = Field(
        description="Key details extracted from the query, like 'specialty' or 'location' for a lawyer search."
    )
    cleaned_query: str = Field(
        description="A concise, clear version of the user's question, best for a database search."
    )

class CustomPydanticOutputParser(PydanticOutputParser):
    """Custom parser that cleans common JSON formatting issues before parsing."""
    
    def parse(self, text: str) -> ParsedQuery:
        # Clean common formatting issues
        cleaned_text = text.strip()
        
        # Remove escaped underscores that break JSON parsing
        cleaned_text = cleaned_text.replace('\\_', '_')
        
        # Remove markdown code blocks if present
        if '```json' in cleaned_text:
            cleaned_text = cleaned_text.split('```json')[1].split('```')[0]
        elif '```' in cleaned_text:
            cleaned_text = cleaned_text.split('```')[1].split('```')[0]
        
        # Try to parse as JSON first to validate
        try:
            json.loads(cleaned_text)
        except json.JSONDecodeError as e:
            # If JSON is invalid, try to fix common issues
            cleaned_text = self._fix_json_issues(cleaned_text)
        
        # Use the parent class parser with cleaned text
        return super().parse(cleaned_text)
    
    def _fix_json_issues(self, text: str) -> str:
        """Fix common JSON formatting issues."""
        # Remove extra spaces around colons and commas
        text = re.sub(r'\s*:\s*', ': ', text)
        text = re.sub(r'\s*,\s*', ', ', text)
        
        # Ensure proper quotes around string values
        text = re.sub(r':\s*([^",{\[\]}\s]+)(?=\s*[,}])', r': "\1"', text)
        
        return text

def get_query_parser_chain():
    """
    Creates and returns a LangChain chain that parses a user query into the ParsedQuery structure.
    """
    # Step 2: Create a custom parser that can handle common formatting issues
    parser = CustomPydanticOutputParser(pydantic_object=ParsedQuery)

    # Step 3: Create a prompt template with detailed instructions for the LLM.
    # It includes the format instructions generated by the parser.
    prompt_template = """
    You are an expert at analyzing user queries for a Sri Lankan legal assistant chatbot.
    Your task is to parse the user's query and format your response as a JSON object.

    - If the user asks about laws, rights, or legal procedures, the intent is 'legal_research'.
    - If the user explicitly asks to find, search for, or be recommended a lawyer, the intent is 'find_lawyer'.
    - For greetings, chit-chat, or off-topic questions, the intent is 'general_question'.

    Extract key entities like 'specialty' and 'location' for lawyer searches.
    The 'cleaned_query' should be a simple, direct version of the user's legal question.

    {format_instructions}

    User Query:
    {query}
    """

    prompt = PromptTemplate(
        template=prompt_template,
        input_variables=["query"],
        partial_variables={"format_instructions": parser.get_format_instructions()},
    )

    # Step 4: Initialize the LLM. We use a low temperature for accuracy.
    # First create the base LLM, then wrap it with ChatHuggingFace
    from langchain_huggingface import HuggingFaceEndpoint
    
    base_llm = HuggingFaceEndpoint(
        repo_id="mistralai/Mistral-7B-Instruct-v0.2",
        temperature=0.1, # Low temperature for precise classification
        huggingfacehub_api_token=os.getenv("HUGGINGFACEHUB_API_TOKEN")
    )
    
    # Now wrap it with ChatHuggingFace (this is the required pattern)
    llm = ChatHuggingFace(llm=base_llm)
    
    # Step 5: Assemble the full chain.
    # The user query goes to the prompt, then to the LLM, and the LLM's output is passed to the parser.
    chain = prompt | llm | parser
    return chain